### ISSUE TITLE
Request: support more than 10 virtual desktops

### ISSUE THREAD

**Issue by petrklus** [sdias/win-10-virtual-desktop-enhancer#10]
Hello!

Would really like to use more than 10 desktops - could the support be enhanced to 20 desktops for example?

My suggestion is to use alternative modifier/modifier combination to access any desktop beyond 10th one

**Comment by sdias** [comment]
Just made it so you can set an additional modifier to do what you said, it will go into the next release. :)

**Comment by sdias** [comment]
Here it is: https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.9.0
Let me know if it works for you!
