### ISSUE TITLE
No difference in option UseNativePrevNextDesktopSwitchingIfConflicting

### ISSUE THREAD

**Issue by tqhao94** [sdias/win-10-virtual-desktop-enhancer#109]
Hello,
I change the option UseNativePrevNextDesktopSwitchingIfConflicting to 1 and 0 but I can't see any differences.
I read the doc but don't really well understand.
Can you explain the impact of it a little more detail please ? 
Thank you.

**Comment by GioBonvi** [comment]
Hello @tqhao94,
enabling that setting will let you keep the "sliding" animation when changing desktops *if* you use the native `Win+Arrow` keyboard shortcut.
