### ISSUE TITLE
interference with desktop switching on task view

### ISSUE THREAD

**Issue by erajsalman** [sdias/win-10-virtual-desktop-enhancer#11]
When I am in taskview I will regularly hover my mouse over other desktops or switch between them using a mouse gesture to see where other windows are. With the script activated, this is not possible. 

If I switch to another desktop while in task view, it will switch, but then pull out of task view. The normal function with the script off is to switch but stay in task view, so it's easier to look at different desktops and then choose to exit task view. 

For the mouse hover, it would show normally preview of different desktops on mouse hover ,but with the script activated, mouse hover will result in switching to the desktop the mouse is over and exiting task view. 

Is there a way to turn these actions off. I would like to be able to stay in task view until I choose to exit.

**Comment by sdias** [comment]
It was a bug. Thanks for reporting it. The fix will go into the next release. :)

**Comment by erajsalman** [comment]
awesome. thank you for the great work!

**Comment by sdias** [comment]
No worries. Here it is: https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.9.0
Let me know if it works for you!

**Comment by erajsalman** [comment]
Working great! thanks!
