### ISSUE TITLE
Desktop wrapping WITH UseNativePrevNextDesktopSwitchingIfConflicting=1

### ISSUE THREAD

**Issue by alphamyd** [sdias/win-10-virtual-desktop-enhancer#112]
Hello!

It's possible to use desktop wrapping with enabled option ’UseNativePrevNextDesktopSwitchingIfConflicting=1’???

I toggle this option, because it toggle on native animation when i change my virtual desktop.

**Comment by sdias** [comment]
This isn't possible at the moment. I'll make a note of it as a future improvement. Thanks.
