### ISSUE TITLE
Windows losing focus after upgrading to Windows April 2018 update

### ISSUE THREAD

**Issue by engwan** [sdias/win-10-virtual-desktop-enhancer#113]
When I switch desktops without clicking on anything, focus is fine. The open application on the desktop gets focused.

But when I switch to desktop 1 for example, and click around. When I go to desktop 2, focus on the open application is lost.

This started happening after I did Windows update.

Anybody have a fix or workaround?

Thanks

**Comment by sdias** [comment]
I've published a new release with fixes, let me know if it works for you.
https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.11.2

**Comment by engwan** [comment]
Thanks, I'll check it out

**Comment by engwan** [comment]
I can confirm that this has been fixed with the latest update. Thanks!
