### ISSUE TITLE
autofocus on desktop doesnt work after windows update

### ISSUE THREAD

**Issue by potpov** [sdias/win-10-virtual-desktop-enhancer#115]
Hi,
after moving to windows 10 version 1803, when i switch to a new desktop the focus remains on the previous one. is there a way to fix this issue?
thanks in advance for any kind of support, i love this app.

**Comment by ovsw** [comment]
Confirmed here, have the same issue.

**Comment by ovsw** [comment]
Updating virtual-desktop-accessor.dll for Win10 v1803 #117 fixes the issue for me

**Comment by sdias** [comment]
I've published a new release with fixes, let me know if it works for you.
https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.11.2
