### ISSUE TITLE
applying new settings without relaunching

### ISSUE THREAD

**Issue by gobbedy** [sdias/win-10-virtual-desktop-enhancer#118]
Fantastic app -- very grateful for it.

I find myself making frequent name changes to my desktops and giving up on the enhancer because applying new settings is too much of a hassle.

Is there a way to apply new settings after modifying settings.ini without having to close the app via task manager and then relaunch it?

If not, a shortcut for applying settings (or worst case, restarting the app) would be very helpful.

**Comment by GioBonvi** [comment]
Hello @gobbedy,
you can reload the app by right-clicking the icon in the task bar and clicking "reload"

**Comment by gobbedy** [comment]
Aaah thanks @GioBonvi you've thought of everything. This tool is so awesome.

The icon/reload feature should be mentioned in the wiki!
