### ISSUE TITLE
Alt+` to switch between windows of same application

### ISSUE THREAD

**Issue by NN---** [sdias/win-10-virtual-desktop-enhancer#120]
Any option to have Alt+` to switch between windows of same application like AltTabAlternative does ?

https://sourceforge.net/projects/alttabalternative/

**Comment by sdias** [comment]
Not at the moment, but I'll keep it in mind as a future improvement. Thanks.

**Comment by NN---** [comment]
I really would like to have all in one application.
There is another which has this feature  https://neosmart.net/EasySwitch/
