### ISSUE TITLE
download does not include exe file

### ISSUE THREAD

**Issue by whburling** [sdias/win-10-virtual-desktop-enhancer#123]
running w10 pro Insider Preview Build 177723
on 30 jul 18 downloaded current win-10-virtual-desktop-enhancer
All I received is the *.ahk file. 
NO exe

am i doing something wrong?  Please help.  I am new at this
Thank you,
bil

**Comment by sdias** [comment]
Hi, can you please download the latest version from here? https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.11.2

Click on the "Windows.10.Virtual.Desktop.Enhancer.0.11.2.zip" link, not on the source code ones.

**Comment by sdias** [comment]
That's quite alright, I'm glad you got it sorted. :)
