### ISSUE TITLE
1809 update broke "move window to next desktop"

### ISSUE THREAD

**Issue by Fanatic17** [sdias/win-10-virtual-desktop-enhancer#131]
Hi everyone and thank you for this awesome script, I just updated to Windows 10 1809 build 17755.1 and i found that the Ctrl + Win + Shift + arrow doesn't move anymore the selected window in the next/ previous desktop. Other features like changing desktop by scrolling on the task bar still work. 

Anyone has any idea on how to fix this?

**Comment by phpcitizen** [comment]
+1

**Comment by TimHendriksen** [comment]
+1

**Comment by bakertony** [comment]
Just updated to insider (just to get dark theme in File Explorer) and dismayed to see that moving windows to other virtual desktops is broke :-(

**Comment by hhu94** [comment]
Similarly, moving a window to a specific desktop doesn't work anymore either.

**Comment by kareltdlg** [comment]
https://github.com/sdias/win-10-virtual-desktop-enhancer/issues/133#issuecomment-427639308 fixes this issue. It works for me.

**Comment by sdias** [comment]
Sorry for not replying earlier. I haven't updated my Windows yet, that's why I haven't released a new version of this to fix it since I can't test it personally. When I do update, I'll release a new version.

**Comment by Fanatic17** [comment]
@sdias thank you for this awesome script, I can confirm that using the referenced library the issue is fixed. I can close this issue.
