### ISSUE TITLE
Tooltip disable doesn't work

### ISSUE THREAD

**Issue by kodx** [sdias/win-10-virtual-desktop-enhancer#17]
Setting Tooltip option to disabled doesn't work.
Tried reload settings and restart application.
Used exe version from Beta 0.9.0.
Windows 10 (Build 14393.693)

**Comment by matedon** [comment]
Yes. The same thing happens with me.

**Comment by vnovichek** [comment]
There is a typo in virtual-desktop-enhancer.ahk:

$ diff virtual-desktop-enhancer-fixed.ahk virtual-desktop-enhancer.ahk
47c47
< global TooltipsEnabled := (TooltipsEnabled != "" and TooltipsEnabled ~= "^[01]$") ? TooltipsEnabled : 1
---
> global TooltipsAreEnabled := (TooltipsAreEnabled != "" and TooltipsAreEnabled ~= "^[01]$") ? TooltipsAreEnabled : 1
236c236
<     if (TooltipsEnabled) {
---
>     if (TooltipsAreEnabled) {

**Comment by vnovichek** [comment]
A quick workaround is to use AreEnabled instead of Enabled in Tooltips section of settings.ini

**Comment by sdias** [comment]
Thanks for reporting, and thanks for identifying the cause. I've uploaded a fixed version ([0.9.1](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.9.1)).
