### ISSUE TITLE
Unchanged Desktop Backgrounds

### ISSUE THREAD

**Issue by alleve** [sdias/win-10-virtual-desktop-enhancer#2]
Hi,

I downloaded and installed Visual C++ Redistributable for Visual Studio 2015.

I edited the settings, saved, then ran the .exe file; however, my desktop backgrounds remained unchanged. Below is a url of what I have entered in the settings file.

Can you help me troubleshoot the issue? I attached my edited "settings" file.

![image](https://cloud.githubusercontent.com/assets/21236326/17960269/f8dccca8-6adf-11e6-8e20-8a312270ffae.png)

Best,

**Comment by sdias** [comment]
Hi. Found the error, thanks for the report. Version Beta 0.6.2 will have the fix.
