### ISSUE TITLE
Option to control wrapping

### ISSUE THREAD

**Issue by drewnoakes** [sdias/win-10-virtual-desktop-enhancer#36]
Could there be an option to disable wrapping from last to first desktop and vice-versa?

**Comment by sdias** [comment]
Yup, I'll do this at some point.

**Comment by sdias** [comment]
Check out https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.3.

**Comment by drewnoakes** [comment]
Very cool!
