### ISSUE TITLE
71 hotkeys have been received in the last 1172ms

### ISSUE THREAD

**Issue by oddboy** [sdias/win-10-virtual-desktop-enhancer#4]
Hi,

great little app, thank you for making it, and making it available for free!

I keep getting a popup about 'x hotkeys have been received'.  I believe it has to do with scrolling as it only pops up when I'm scrolling.  I have disabled Scroll switching in the settings file, but it still happens.

is there a way to suppress that alert?  the alert asks me when I want to continue to which I hit the Yes button and everything trucks along without issue.

thanks!

Joel

**Comment by samr1953** [comment]
I'm having this problem as well. Suggestions?

**Comment by oddboy** [comment]
Hi samr, I ended up installing AutoHotKey and using the ahk script file.  I set the following at the top of the 'virtual-desktop-enhancer.ahk' script:

#HotkeyInterval 20  ; This is  the default value (milliseconds).
#MaxHotkeysPerInterval 20000

since then, I have not had the popup.

cheers,

Joel

**Comment by samr1953** [comment]
Thanks! I'll give it a try.

...Sam

**Comment by as14** [comment]
I am having the same problem with the scroll whell (when scrolling a lot / fast, getting the popup).  It says to "see #MaxHotkeysPerInterval in the help file", but I don't see a help file anywhere, nor do I see any setting for MaxHotkeysPerInterval in settings.ini.

I tried adding the following to virtual-desktop-enhancer.ahk as @oddboy suggested, but it doesn't appear to do anything without AutoHotKey installed, even after I reload the settings in Virtual Desktop Enhancer
#HotkeyInterval 20 ; This is the default value (milliseconds).
#MaxHotkeysPerInterval 20000

Is there anyway to fix this without installing AutoHotKey?  Maybe @sdias knows

**Comment by oddboy** [comment]
As far as I can tell, editing the ahk script has no effect on the .exe compiled version of the app.

So what I did was to install AutoHotKey, and use the .ahk script instead of the .exe.  You only need one or the other.

**Comment by as14** [comment]
@oddboy .....gotchya....thanks for the advice....and the quick reply.

I see that there are the following .ahk files in the Virtual Desktop Enhancer folder.  Are they all needed once AutoHotKey is installed?
- read-ini.ahk
- tooltip.ahk
- virtual-desktop-enhancer.ahk
- tooltip.ahk

Also, when using AutoHotKey instead of Virtual Desktop Enhancer, will I still be able to use taskbar scrolling or have the icon on the taskbar display the current desktop number?

**Comment by samr1953** [comment]
I tried this two days ago and so far it has cleared up the problem. Thanks!

**Comment by oddboy** [comment]
As14, yes, you need them all, and yes, you will still have the scrolling and systray icon.  I think the exe just bundles the ahk script and the ahk interpreter into one exe file.

I also added a shortcut to my startup folder that shortcuts to the ahk file so it starts when I log in. 

I'm a happy camper.

**Comment by as14** [comment]
oddboy.....thanks for that info and yet another quick reply.....I will install AutoHotKey and remove Virtual Desktop Enhancer, and see how that works.

**Comment by sdias** [comment]
Hi guys, sorry for not replying sooner. Thanks for reporting the issue and also providing a solution, I'll push an updated version with oddboy's fix. Thanks again.

**Comment by as14** [comment]
I tried making the modifications to the .ahk files, and it worked perfectly.  Thanks!
