### ISSUE TITLE
Installation - can't find .exe

### ISSUE THREAD

**Issue by mfells** [sdias/win-10-virtual-desktop-enhancer#42]
I just downloaded and the .exe doesn't seem to exist.  I have tried searching GitHub and can't find it there - do you know what I might be doing wrong?

I also tried the AutoHotkey approach but that resulted in "Error: Can't load icon.  Specifically: icons/+.ico .  The starting line # is 511.

I have Win 10 Home, 64-bit. (The 'free' update from Win 8.x but now upgrader to the Creator edition ... specifically: Version 1703 (OS Build 15063.250))

This tool looks fantastic and I really, really, really want it! Any help is GREATLY appreciate.

MF

**Comment by sdias** [comment]
Hi, thanks. Please check the releases page: https://github.com/sdias/win-10-virtual-desktop-enhancer/releases.
The executables are only available on releases. Also, there have been reports of issues running this app with the Creators Update installed, please let me know how it goes for you on this thread: https://github.com/sdias/win-10-virtual-desktop-enhancer/issues/39
