### ISSUE TITLE
Feature proposal: more tooltip customization

### ISSUE THREAD

**Issue by GioBonvi** [sdias/win-10-virtual-desktop-enhancer#47]
I find that having more customizable toasts could be a useful feature. The options I thought of are:

- fade out animation duration (currently fixed at 100ms
- position (currently center or bottom-right corner): I thought of something like `xPos: LEFT, CENTER, RIGHT; yPos: TOP CENTER BOTTOM` to get all the combinations easily

If you approve this I can code this features into my last pull request #46

**Comment by GioBonvi** [comment]
Will do then!

This weekend I should be able to further test my PR on multi-monitor tooltips as well.

**Comment by sdias** [comment]
[Published!](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.4) Thanks.
