### ISSUE TITLE
Beta 0.10.3 .zip is wrong file format.

### ISSUE THREAD

**Issue by jed-frey** [sdias/win-10-virtual-desktop-enhancer#49]
It's actually a .7z file. Windows 10 complains that it is an invalid type.

7-Zip will warn you that it's an invalid .zip so it's opening it as a .7z.

For people without 7-Zip installed they probably can't open release.

**Comment by GioBonvi** [comment]
Yep, confirm this!

**Comment by sdias** [comment]
Thanks, I'll fix it later.

**Comment by sdias** [comment]
Done, I created it with PeaZip this time around, let me know if it doesn't work.
https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.3
