### ISSUE TITLE
Feature Request - taskbar scrolling on multiple monitors

### ISSUE THREAD

**Issue by as14** [sdias/win-10-virtual-desktop-enhancer#5]
After setting TaskbarScrollSwitching to 1 in settings.ini, I am able to scroll on the taskbar on my 1st monitor, but not on the taskbars on other monitors.  Would be great to be able to do that too.

**Comment by sdias** [comment]
Hi. Unfortunately I only have the one, so I can't really implement this for several monitors. Sorry about that.

**Comment by as14** [comment]
@sdias No worries.....I decided to download AHK and learn a bit about it.  It is REALLY powerful!  Glad I did that.

Looks like the problem was in the IsCursorHoveringTaskbar() method of virtual-desktop-enhancer.ahk.  That method used
`WinGet, taskbarID, ID, ahk_class Shell_TrayWnd`
to check if the cursor was on top of the taskbar.  Problem was that ahk_class Shell_TrayWnd only applies to the taskbar on the primary monitor.

To solve the problem, I re-wrote that method as such:
```
IsCursorHoveringTaskbar() {
    ; --------------------------------------------------------------
    ;            get current Mouse Coordinates
    ; --------------------------------------------------------------
    CoordMode Mouse, Screen
    MouseGetPos, mouseCurrentX, mouseCurrentY
    CoordMode Mouse
    
    ; --------------------------------------------------------------
    ;            get work area bottom for current monitor
    ; --------------------------------------------------------------
    workAreaBottom := -1                                ; value used to test and make sure something was set
    SysGet, monCount, MonitorCount                      ; find the number of monitors
    loop %monCount%                                     ; for every monitor
    {
        SysGet, curMon, Monitor, %a_index%              ; get coordinates of current monitor to test if the mouse is inside the coordinates of the current monitor
        if ( mouseCurrentX >= curMonLeft and mouseCurrentX <= curMonRight and mouseCurrentY >= curMonTop and mouseCurrentY <= curMonBottom )
            {                                           ;  if the mouse is inside the current monitor's coordinates
				SysGet, curMonWorkArea, MonitorWorkArea, %a_index%          ; get the Work Area of the current monitor (excludes the taskbar)
                workAreaBottom := curMonWorkAreaBottom                      ; set the value for workAreaBottom to be equal to the bottom coordinate of the current monitor's work area
			}
    }
    
    return (workAreaBottom != -1 and mouseCurrentY > workAreaBottom)
}
```


This gets the cursor's current position, gets the number of monitors, loops through all monitors to find out which monitor the cursor is currently on, and then checks to see if the cursor is inside of the workspace for the current monitor (workspace doesn't include the task bar).

Note that the method only works if the taskbar is at the bottom of the screen.  If it were at the top (or on a side), you would have to tweak the method a little, but it wouldn't be too hard to do.

**Comment by sdias** [comment]
Thanks for the solution, great to see you're enjoying AHK.
