### ISSUE TITLE
A way to start program when computer starts?

### ISSUE THREAD

**Issue by boxler** [sdias/win-10-virtual-desktop-enhancer#50]
I was wondering if there is a way to make this program start when my computer starts. I tried adding it to my startup folder (C:\Users\Brad\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup), but when I do that, it cannot seem to find its associated files that are located on the desktop. When I add all of the files to the startup folder, it does not work either and ends up opening files that don't need to be opened (i.e. notepad docs and the pictures for the desktop backgrounds). I am wondering if anyone has a solution to this. Sorry I'm new to this.

I created an AHK script that sort of solved this problem; however, it only works some of the time. If another startup program opens at the same time that it is running, it will sometimes be interfered with and not work. Here is that script:

`Sleep 8000
Send, {LWin down}
Send, {LWin up}
Sleep 1000
Send, virtual-desktop-enhancer.ahk
Sleep 2000
Send, {AppsKey}
Sleep 1000
Send, {down}
Sleep 500
Send, {down}
Sleep 500
Send, {enter}
Sleep 3000
Send, {enter}
Sleep 500
Send, !{f4}`

**Comment by GioBonvi** [comment]
Hello, @boxler 

To make the program start up at login go to the folder where you saved the executable and the other files related to the program, right click on the executable -> "Send to" -> "Desktop (create shortcut)".  
This should create a shortcut for the program on your desktop: right click on it, cut it, go to your startup folder (`C:\Users\Brad\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`) and paste it there.

Now restart your computer and it should automatically launch it when you login.

Let me know if this helps you.

Ps: if you change the location of the program files  files (e.g. if you move them from the desktop to another folder) the shortcut will break: just repeat the procedure replacing the old shortcut with the new one.

**Comment by boxler** [comment]
@GioBonvi That got it to work! Thank you so much for your help!
