### ISSUE TITLE
Feature Request - Tooltips on all monitors

### ISSUE THREAD

**Issue by as14** [sdias/win-10-virtual-desktop-enhancer#6]
Would be great to be able to see tooltips on all my monitors.

**Comment by sdias** [comment]
Hi. Unfortunately I only have the one, so I can't really implement this for several monitors. Sorry about that.

**Comment by as14** [comment]
@sdias I figured out how to do this, but went a bit overboard on my solution (tooltips on upto 10 monitors, ability to toggle the tips on/off for each individual monitor, ability to add the workspace number to the tooltip, ability to add time / date / day of week to the tool tip, custom fonts and font sizes for the various text, etc.), and it is thus quite long / complex.....probably not worth posting here unless you really want me to.

**Comment by dharmaturtle** [comment]
@as14 I, for one, would be interested! You should fork :)

**Comment by as14** [comment]
@dharmaturtle I have never forked anything, and not really sure about how it works.  I can post here though if it is OK with @sdias

**Comment by sdias** [comment]
@as14 That sounds amazing, any chance you could share it?

**Comment by sdias** [comment]
[Implemented by @GioBonvi.](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.4)
