### ISSUE TITLE
Rename virtual desktops at run time

### ISSUE THREAD

**Issue by achim-t** [sdias/win-10-virtual-desktop-enhancer#60]
I would like to rename a Virtual Desktop at run time, persisting those names is not necessary for me.

**Comment by GioBonvi** [comment]
Hello @achim-t 

I am sorry, but I don't think I understand what you are asking. Do you want to rename a desktop in the task view (as in #55)? If this is what you want then I'm sorry to inform you that, as stated in that issue this is not possible.
Otherwise, if you want to change the desktop names shown in the pop-ups please refer to the [documentation](https://sdias.github.io/win-10-virtual-desktop-enhancer/docs/settings.html#desktop-names).

Best regards

**Comment by achim-t** [comment]
I want to change the names shown in the pop-ups, but I don't want to use the same names every time.

**Comment by GioBonvi** [comment]
Ok, thank you for the clarification, now I understand: this is not a supported feature, but maybe there is something I can do.

According to what do you want the names to change?

**Comment by achim-t** [comment]
I want to change it according to the task at hand.

I was imagining a shortcut like CTRL+WIN+F2 that opens up a prompt where I can enter a name like "Heavy Browsing" or "Work for Client X".

**Comment by GioBonvi** [comment]
Ok, so you want to be able to manually change desktop names "on the run". I think this could definitely be a nice addition.

In fact I was thinking of something similar the other day, however in the next weeks I won't be able to dedicate time to this project at all.  
I'll notify you on this issue about any news and updates.

**Comment by achim-t** [comment]
Thanks.

**Comment by GioBonvi** [comment]
I finally found some time to think about this: I ditched my previous idea about a more complex and complete system in favor of a simpler approach. Hope this helps.

Will let you know if this is merged into master.

**Comment by GioBonvi** [comment]
Hello, @achim-t

your suggestion has been implemented in the last version of the program: the release for it should be published really soon.

**Comment by achim-t** [comment]
Thank you, great work.

**Comment by achim-t** [comment]
A small issue (should I create a new Issue?): 

After renaming, the Tray Tooltip still shows the old name for the moment.

**Comment by GioBonvi** [comment]
Thank you for noticing and rerporting this: I will fix this the next time I will work on this project.

**Comment by GioBonvi** [comment]
FIxed and published in the new release.

Thank you again @achim-t.
