### ISSUE TITLE
Taskbar scrolling should work on secondary taskbar as well

### ISSUE THREAD

**Issue by achim-t** [sdias/win-10-virtual-desktop-enhancer#61]
The secondary taskbar has a different ahk_class: `Shell_SecondaryTrayWnd` instead of `Shell_TrayWnd`.

**Comment by sdias** [comment]
Agreed, fixing it.

**Comment by sdias** [comment]
Done: https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.5.

**Comment by achim-t** [comment]
Thanks a lot.
