### ISSUE TITLE
Branch origin/master

### ISSUE THREAD

**Issue by GioBonvi** [sdias/win-10-virtual-desktop-enhancer#62]
@sdias 
It looks like there is something wrong with the [branches](https://github.com/sdias/win-10-virtual-desktop-enhancer/branches): last version was released on a new branch called `origin/master` instead of `master`.

**Comment by sdias** [comment]
I probably messed it up. I'll look into it when I get home.

**Comment by sdias** [comment]
`master` now has all of the changes, and I deleted all of the other branches, except for `toggle-last-desktop`, which still has your unpublished changes for that feature.
