### ISSUE TITLE
Can't get anything to work

### ISSUE THREAD

**Issue by nuteguy** [sdias/win-10-virtual-desktop-enhancer#63]
I installed the latest version of the program, extracted it to a folder on my desktop, and ran it as an admin. When I run the program all that shows up on my tray is a little green H for autohotkey. No shortcuts work; windows or the ones found in the settings file. I can't change my desktop wallpapers or rename the desktops. The only thing that does work is win+tab and Lalt+SC029. I'll gladly answer any questions and provide more information. Thanks

**Comment by GioBonvi** [comment]
Hello, @nuteguy, thank you for writing in and sorry for the troubles you are experiencing.

As you can read [here](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/known-issues.md#programs-run-as-another-user) it is known that Windows 10 Virtual Desktop Enhacner has a _troublesome relationship_ with the "run as" command, in particular if you run it as another account (like Adminstrator) and your account does not have administrative rights it will not work at all like you are describing.

Running it normally should make it work: why were you running it as administrator in the first place?
Were you trying to solve other problems?

Best regards

**Comment by nuteguy** [comment]
I tried to run it normally since my account has admin privileges but it still didn't work so I also tried to run it as an admin with no luck. My bad on not being clear.

**Comment by GioBonvi** [comment]
So you tried running it via double click and it did not work with displaying the symptoms described in your first post, then you tried running it as administrator and nothing changed, right?

Does your system match the requirements? (Windows 10 64 bit with Creators Update installed)?

Secondly (this might sound silly, but it's better to be safe than sorry) are you sure you have more than one virtual desktop active?

**Comment by nuteguy** [comment]
Correct. How can I check if I have the Creators Update installed? and yeah I have three desktops haha.

**Comment by GioBonvi** [comment]
To identify your current Windows version use the Windows key + R keyboard shortcut to open the Run command.  
Type ‘winver’ in the box.  
Click OK.  
If the version is 1608 or greater you have the Anniversary Update installed and if it also greater or equal to 1703 you have the Creator Update as well.

Have you already tried installing [this component](https://www.microsoft.com/en-us/download/details.aspx?id=52685) as suggested in the [documentation](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/installation.md)?  
Please restart the computer after the installation.

**Comment by nuteguy** [comment]
I have version 1703. I haven't tried that yet but will right now.

**Comment by GioBonvi** [comment]
This pretty much exhausted all the easy options.if the additional component will not fix the issue I will mark this as a bug and tomorrow will proceed with some extra-intense debugging ;-)

**Comment by nuteguy** [comment]
That did the trick! Thank you so much. I'm not sure how I missed that in my reading of the install instructions.

**Comment by GioBonvi** [comment]
That's great!

Marking the issue as solved.
