### ISSUE TITLE
_Focus() function causes full screen pages to exit by sending Alt + Esc key combo

### ISSUE THREAD

**Issue by nuteguy** [sdias/win-10-virtual-desktop-enhancer#64]
When watching a youtube video in full screen and switching to another desktop and back, fullscreen exits. Just an observation. If I had to guess it has to do with the custom wallpaper which needs to update but I don't know that for sure.

**Comment by GioBonvi** [comment]
Actaullay it looks it all boils down to [line 547 of the AHK script](https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/virtual-desktop-enhancer.ahk#L547).
```autohotkey
OnDesktopSwitch(n:=1) {
    if (TooltipsEnabled) {
        _ShowTooltipForDesktopSwitch(n)
    }
    _ChangeAppearance(n)
    _ChangeBackground(n)
    _FocusIfRequested()

    if (previousDesktopNo) {
        _RunProgramWhenSwitchingFromDesktop(previousDesktopNo)
    }
    _RunProgramWhenSwitchingToDesktop(n)
    previousDesktopNo := n
}
```

```autohotkey
_FocusIfRequested() {
    if (doFocusAfterNextSwitch) {
        _Focus()
        doFocusAfterNextSwitch=0
    }
}

_Focus() {
    WinActivate, ahk_class Shell_TrayWnd
    SendEvent !{Esc} ; <-- This is the culprit
}
```

This makes sense as the `Esc` key is used to exit from full screen in many applications and Youtube is one of them.  
If that line is removed full screen stays open after a desktop switch, however the task bar remains visible (even on full screen), which possibly is the reason for that command to be there.

I've tried commenting out the  `_FocusIfRequested()` call from the `OnDesktopSwitch` function and it actually looks like this solves the issue: full screen is preserved and the taskbar is not visible.  
Doing this however introduces problems with focus consistence across differents desktops (you might land on a desktop and not have any window having focus) and this is to be expected as that function call probably had a reason to be there ;-)
@sdias might be able to give some more details: is there anything that could replace the `SendEvent !{Esc}` line? I am not sure I understood what actually happens in these two focus functions.

**Comment by sdias** [comment]
@nuteguy @GioBonvi That's pretty much it Gio, good work. That line of code is there to make sure you focus on the last active window of that desktop, because (I think?) nothing will be focused otherwise, but I can't remember exactly how necessary it is, and there are probably better ways of handling that. For now, I suggest to anyone interested to try to comment out the contents of the '_Focus()' function and using the app like that, to see if they run into any focus issues. I'll be doing the same.

**Comment by GioBonvi** [comment]
Solved in the [latest release](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.11.0).

Thank you @nuteguy for the bug report.
