### ISSUE TITLE
Launch multiple programs on desktop entry/exit?

### ISSUE THREAD

**Issue by janus0** [sdias/win-10-virtual-desktop-enhancer#73]
Is there a way I could set this up so that I could launch my notes and a web browser for instance when switching to desktop n? Thanks!

**Comment by janus0** [comment]
Nm, I figured out that I can simply point virtual desktop enhancer to a batch file that launches multiple programs.

**Comment by GioBonvi** [comment]
You could also separate multiple commands with `&` like in `calc.exe & notepad.exe`.
