### ISSUE TITLE
Independent Virtual Desktops

### ISSUE THREAD

**Issue by Retiixx** [sdias/win-10-virtual-desktop-enhancer#8]
Hi, thanks for this enhancer, just wondering if a feature is possible to implement.
I have a multi-monitor setup, is there a way to manage virtual desktop independently, so I can let "Desktop 1" on one monitor and switch between VD on the other monitors ?

Thanks

**Comment by sdias** [comment]
Hi, thanks for using it.

That isn't really possible. A virtual desktop includes all of the monitors,
so if you switch desktops, you switch the view for every monitor. That's
how most virtual desktop systems are implemented.

One thing that could be useful for you is to display a window across all of
your virtual desktops, which unfortunately is not possible using Windows
virtual desktops, as far as I know.

**Comment by vandasian** [comment]
With 1607 you can right-click on a window in Task View and select Show this window on all desktops

**Comment by Retiixx** [comment]
Thanks @vandasian for the tip. It's working great ! Exactly what I wanted !
