### ISSUE TITLE
Switch on Alt N

### ISSUE THREAD

**Issue by refeaime** [sdias/win-10-virtual-desktop-enhancer#85]
Hello, 
HUGE thanks for this script. I am old DWM user on linux system and wondering, how properly set same tag\virtual_desktop in windows by pressing ALT+N, where N is number line. 
What in that case [KeyboardShortcutsCombinations] section would looks like? 
Thank you.

**Comment by dobin** [comment]
```
[KeyboardShortcutsModifiers]
SwitchDesktop=Alt
```

**Comment by sdias** [comment]
Dobin's right, that config should work. Please have a look at the Customization part of the README.

**Comment by dobin** [comment]
It has some drawbacks, e.g. Alt-Left in Word, or Explorer, will be broken.
