### ISSUE TITLE
Feature Request - Run command on change

### ISSUE THREAD

**Issue by Starofall** [sdias/win-10-virtual-desktop-enhancer#9]
It would be nice to run a specific file on enter and leaving a desktop.

[RunFileOnEnter]
1=C:\Programs\....\foo.bat

[RunFileOnLeave]
1=C:\Programs\....\foo.bat

**Comment by sdias** [comment]
I'm not sure how useful this would be... Can you give an example?

**Comment by Starofall** [comment]
Sure.
I use this tool to seperate different "working environments". 

Ideas:
- If I am working on two projects, I might want to run start docker containers once I entered a desktop and stop them when I am leaving.
- Start a timer to track the amount of time I spend on this project
- Change the color of my behind-monitor-leds
- Changeing environment variables based on the desktop I work on
- Start IDE/tools when I enter a desktop and they are not started yet

With this feature and .bat files I could implement all this for me.

**Comment by sdias** [comment]
Sounds reasonable. I'll try to get this into the next release.

**Comment by sdias** [comment]
@Starofall [Just published a release with this change](https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.10.2), let me know how it works for you.

**Comment by Starofall** [comment]
@sdias thank you! It works as expected 👍
