### ISSUE TITLE
Feature Request: Keep one moniter constant multiple moniters

### ISSUE THREAD

**Issue by keluecke** [sdias/win-10-virtual-desktop-enhancer#96]
Love the application, thank you for your work!

 One feature I miss from Linux is the ability to keep one of my monitors constant for things like controlling music or a conversation.  Could also be accomplished with an option to make programs as move with me whenever I change desktops (either through listing them or through marking the currently selected app as carry along with a hotkey).

**Comment by sdias** [comment]
Hi, thanks.
Keeping the all of the apps in a monitor pinned across desktops is not supported, but you can pin an app or the window of an app already. Please see the guide here: https://github.com/sdias/win-10-virtual-desktop-enhancer/blob/master/docs/settings.md#keyboard-shortcuts-identifier-keys
